# Generated by Django 4.2.5 on 2023-10-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grievanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=500)),
                ('aadhar_card', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=1000)),
                ('issue', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
