# Generated by Django 4.2.5 on 2023-10-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievanceapp', '0002_alter_grievanceform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievanceform',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
